#!/bin/bash

# delete old zip
rm similar_author.zip

# add language detection directory
zip -r similar_author.zip res/langdetect-03-03-2014/profiles/ 

# add models for POS tagging
zip similar_author.zip res/stanford-postagger-full-2014-08-27/models/german-fast.tagger
zip similar_author.zip res/stanford-postagger-full-2014-08-27/models/english-left3words-distsim.tagger

# add resource files with function words
zip similar_author.zip res/FunctionWords_de.txt
zip similar_author.zip res/FunctionWords_en.txt

# add resource files with abbreviations
zip similar_author.zip res/Abbreviations_de.txt
zip similar_author.zip res/Abbreviations_en.txt

# add all files generated by intelliJ
cd build/classes/artifacts/similar_author_identification_jar/
zip -r ../../../../similar_author.zip *